/* 
    States for CRUD
*/
export const SEARCHING = "SEARCHING"
export const INSERTING = "INSERTING"
export const EDITING   = "EDITING"

/*
    States para FICHA
*/
export const STATE_CADASTRO                 = "STATE_CADASTRO"
export const STATE_CUSTODIADOS              = "STATE_CUSTODIADOS"
export const STATE_BLACKLIST                = "STATE_BLACKLIST"
export const STATE_BLOQUEIOS                = "STATE_BLOQUEIOS"
export const STATE_VISITA                   = "STATE_VISITA"
export const STATE_ADVOGADO                 = "STATE_ADVOGADO"
export const STATE_BIOMETRIA                = "STATE_BIOMETRIA"
export const STATE_COMPANHEIROS_CELA        = "STATE_COMPANHEIROS_CELA"
export const STATE_MOVIMENTACOES            = "STATE_MOVIMENTACOES"
export const STATE_HISTORICO_VISITAS        = "STATE_HISTORICO_VISITAS"
export const STATE_HISTORICO_LOTACAO        = "STATE_HISTORICO_LOTACAO"
export const STATE_AFASTAMENTO_SERVIDOR     = "STATE_AFASTAMENTO_SERVIDOR"
export const STATE_OFICIO_SERVIDOR          = "STATE_OFICIO_SERVIDOR"
export const STATE_PROCESSOS                = "STATE_PROCESSOS"
export const STATE_SAUDE                    = "STATE_SAUDE"
export const STATE_ARQUIVO                  = "STATE_ARQUIVO"
export const STATE_UNIDADE_ACESSO           = "STATE_UNIDADE_ACESSO"
export const STATE_CERTIDAO_CARCERARIA      = "STATE_CERTIDAO_CARCERARIA"
export const STATE_COMPORTAMENTO_CARCERARIO = "STATE_COMPORTAMENTO_CARCERARIO"
export const STATE_OUTRO_NOME               = "STATE_OUTRO_NOME"
export const STATE_DIAS_TRABALHO            = "STATE_DIAS_TRABALHO"
export const STATE_SITUACAO_JURIDICA        = "STATE_SITUACAO_JURIDICA"
export const STATE_CARTEIRAS                = "STATE_CARTEIRAS"
export const STATE_FAMILIA                  = "STATE_FAMILIA"
export const STATE_JURIDICO                 = "STATE_JURIDICO"
export const STATE_ALBERGADO                = "STATE_ALBERGADO"

/*
    States para RELATÓRIO
*/

export const STATE_SINTETICO = "STATE_SINTETICO"
export const STATE_ANALITICO = "STATE_ANALITICO"

/*
    States para TELA DE RELATÓRIO GERAL DE ESTATÍSTICAS
*/

export const STATE_RELATORIO_POPULACAO_CARCERARIA = "STATE_RELATORIO_POPULACAO_CARCERARIA"
export const STATE_RELATORIO_POPULACAO_CARCERARIA_RESUMO = "STATE_RELATORIO_POPULACAO_CARCERARIA_RESUMO"
export const STATE_RELATORIO_BIOMETRIA = "STATE_RELATORIO_BIOMETRIA"
export const STATE_RELATORIO_DEPEN_CRIME = "STATE_RELATORIO_DEPEN_CRIME"
export const STATE_RELATORIO_SAUDE_ATENDIMENTO_MEDICO = "STATE_RELATORIO_SAUDE_ATENDIMENTO_MEDICO"
export const STATE_RELATORIO_SAUDE_MEDICAMENTO = "STATE_RELATORIO_SAUDE_MEDICAMENTO"
export const STATE_RELATORIO_SAUDE_PATOLOGIA = "STATE_RELATORIO_SAUDE_PATOLOGIA"
export const STATE_RELATORIO_SAUDE_VACINA = "STATE_RELATORIO_SAUDE_VACINA"
export const STATE_RELATORIO_TERMINAL_ENTRADA_SAIDA = "RELATORIO_TERMINAL_ENTRADA_SAIDA"
export const STATE_RELATORIO_TERMINAL_LOG = "RELATORIO_TERMINAL_LOG"
export const STATE_RELATORIO_JURIDICO_ATIVIDADE = "RELATORIO_JURIDICO_ATIVIDADE"
export const STATE_RELATORIO_REINCIDENCIA = "RELATORIO_REINCIDENCIA"
export const STATE_RELATORIO_TRANSFERENCIA_UNIDADE = "RELATORIO_TRANSFERENCIA_UNIDADE"
export const STATE_RELATORIO_SINTETICO_SAIDA_TEMPORARIA = "STATE_RELATORIO_SINTETICO_SAIDA_TEMPORARIA"
export const STATE_RELATORIO_SINTETICO_ENTRADA_DELEGACIA = "STATE_RELATORIO_SINTETICO_ENTRADA_DELEGACIA"
export const STATE_RELATORIO_JURIDICO_PROCESSO = "RELATORIO_JURIDICO_PROCESSO"
export const STATE_RELATORIO_JURIDICO_INCIDENCIA = "RELATORIO_JURIDICO_INCIDENCIA"
export const STATE_RELATORIO_ANEXO = "RELATORIO_ANEXO"
export const STATE_RELATORIO_ALBERGADO_PRESENCA_FILIACAO = "RELATORIO_ALBERGADO_PRESENCA_FILIACAO"
export const STATE_RELATORIO_ALBERGADO_PRESENCAS = "RELATORIO_ALBERGADO_PRESENCAS"
export const STATE_RELATORIO_COMPANHEIROS_LOCALIZACAO = "RELATORIO_COMPANHEIROS_LOCALIZACAO"

/*
    States para TELA DE RELATÓRIO GERAL SERVIDOR
*/

export const STATE_RELATORIO_SERVIDOR_ANALITICO_SINTETICO = "STATE_RELATORIO_SERVIDOR_ANALITICO_SINTETICO"
export const STATE_RELATORIO_SERVIDOR_HISTORICO_LOTACAO   = "STATE_RELATORIO_SERVIDOR_HISTORICO_LOTACAO"
export const STATE_RELATORIO_SERVIDOR_AGENDAMENTO_SAP   = "STATE_RELATORIO_SERVIDOR_AGENDAMENTO_SAP"

/*
    States para TELA DE RELATÓRIO GERAL DE AUDITÓRIAS
*/

export const STATE_RELATORIO_AUDITORIA_FICHA_CUSTODIADO = "STATE_RELATORIO_AUDITORIA_FICHA_CUSTODIADO"
export const STATE_RELATORIO_AUDITORIA_PESSOA_RELACAO = "STATE_RELATORIO_AUDITORIA_PESSOA_RELACAO"
export const STATE_RELATORIO_AUDITORIA_FICHA_SERVIDOR = "STATE_RELATORIO_AUDITORIA_FICHA_SERVIDOR"

/*
    States para TELA GERAL DE CRUD DE TABELAS DOMÍNIO
*/

export const STATE_CRUD_SAUDE_VACINA = "STATE_CRUD_SAUDE_VACINA"
export const STATE_CRUD_SAUDE_MEDICAMENTO = "STATE_CRUD_SAUDE_MEDICAMENTO"
export const STATE_CRUD_SAUDE_PATOLOGIA = "STATE_CRUD_SAUDE_PATOLOGIA"
export const STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA = "STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA"
export const STATE_CRUD_TERMINAL = "STATE_CRUD_TERMINAL"
export const STATE_CRUD_INSTITUICAO = "STATE_CRUD_INSTITUICAO"

/*
    States para TELA GERAL DE CRUD DE TABELAS DOMÍNIO SERVIDOR
*/

export const STATE_CRUD_LEI_SERVIDOR = "STATE_CRUD_LEI_SERVIDOR"
export const STATE_CRUD_EDITAL_SERVIDOR = "STATE_CRUD_EDITAL_SERVIDOR"
export const STATE_CRUD_CARGO_SERVIDOR = "STATE_CRUD_CARGO_SERVIDOR"
export const STATE_CRUD_TIPO_VINCULO_SERVIDOR = "STATE_CRUD_TIPO_VINCULO_SERVIDOR"
export const STATE_CRUD_ORGAO_ORIGEM_SERVIDOR = "STATE_CRUD_ORGAO_ORIGEM_SERVIDOR"


/*
    States para TELA GERAL DE AUTORIZAÇÃO DE ENTRADA NAS UNIDADES PRISIONAIS
*/

export const STATE_AUTORIZACAO_ENTRADA_GERAL = "STATE_AUTORIZACAO_ENTRADA_GERAL"
export const STATE_AUTORIZACAO_ENTRADA_VISITANTE = "STATE_AUTORIZACAO_ENTRADA_VISITANTE"
export const STATE_AUTORIZACAO_AGENDAMENTO_JURIDICO = "STATE_AUTORIZACAO_AGENDAMENTO_JURIDICO"
export const STATE_AUTORIZACAO_AGENDAMENTO_SOCIAL = "STATE_AUTORIZACAO_AGENDAMENTO_SOCIAL"


/*
    States para TELA GERAL DE RELATÓRIOS DE VISITAS (GERAL E COM SENHAS AGENDADAS)
*/

export const STATE_RELATORIO_VISITA_GERAL = "STATE_RELATORIO_VISITA_GERAL"
export const STATE_RELATORIO_VISITA_SENHA = "STATE_RELATORIO_VISITA_SENHA"
export const STATE_RELATORIO_VISITA_AGENDAMENTO_JURIDICO = "STATE_RELATORIO_VISITA_AGENDAMENTO_JURIDICO"
export const STATE_RELATORIO_VISITA_AGENDAMENTO_SOCIAL = "STATE_RELATORIO_VISITA_AGENDAMENTO_SOCIAL"